apiVersion: v1
data:
    password: ENC[AES256_GCM,data:zPT5IPcfLS3GsY+l,iv:wq6e+q7Qngnx7dAbrjI5yFriEssdSp4zoPolNiGqB+E=,tag:PAdQZEdeNXymK6xm4eflfw==,type:str]
    username: ENC[AES256_GCM,data:58UCDye7UQ0=,iv:PB8kYQF0Ugh1ZBVfNnLrY0PeshUhDal4xopjQ9R5h2Y=,tag:Hvk1GO1XVy8K/QsFvzNh6Q==,type:str]
kind: Secret
metadata:
    name: forgejo-admin-secret
    namespace: forgejo
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1cjRQUG9FR0V2NExwUm9t
            OXRhMGFaS1NTS3NhVHMraEJDdUxtdDRvM1RvCjdWazIrNlhaOHkwNkIvMEp1ZkVN
            cmh1Z2J4Q1QrdlBkWm4rTVNYc3Y0bDQKLS0tIGY4b0l5NDJwY0RvVjdYWDVidW5n
            bFppVHd0SUdxMktuWkZKWTNQUTg3cUkK6u8tkTUWpZ9KHKwOYJLlbO23jyFGRa+o
            vPlJmE7NeKx+4XsElXd+avvkM4QyQ80bPjyqq3umYMyIWojoRjZdDQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d2hgv8jl3kn3t26f68cpqxy26cd2qpk5af77x832ephn8qhszgssthjfjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T09:16:52Z"
    mac: ENC[AES256_GCM,data:5JDvSmqb2ZdnI3C2BXb0AIV9cJGZ0xiG9x1xBoxELa7QC5MYLaAafAFoyhfC2WKQVFuY5sccQp5fvnuS8haCW75u8Ab1XbCjkUqYaJbo+RJO9CIp0MQAVWcL8Jn4V7MAH5IWHZdlHVDFt/FbBj120mRIYzlij8CYyYKLA1uYDXs=,iv:sbj66dWv1M/rJocR0XCl5RT6NJ6wOJQBAJUJ+n9nGeE=,tag:cpkej+ZrvlyigE5zQx4uvA==,type:str]
    version: 3.13.3
