apiVersion: v1
data:
    password: ENC[AES256_GCM,data:AsxahEeHIDZN09a8,iv:EIcaxgz/LooxeviUS8GQ+pj+slCsNeWny0SG9uEKPo8=,tag:nDLq2SCXsM109tl6HXQ+Ow==,type:str]
    username: ENC[AES256_GCM,data:Y/iVBL1Mmr/VR3ZnjWlTFQzN918=,iv:CuhL/v2sozpvXO+5F1R9tuKpBIx5br3EKgwchCkS0HI=,tag:Gmmq3VjJWRBmcLn6uc5Yzg==,type:str]
kind: Secret
metadata:
    name: forgejo-admin-secret
    namespace: forgejo
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdll3OE5DTTRCbHlzYkpU
            ZGJWUmRLdjlveGI5cE5tNXlZSndxVlVnaWhBClZUcWRmd2JUTDlsL0Fvc0dJdGdz
            U1dUaFdVVkxIQU02aEZMMWZPMnZqK2sKLS0tIGNQRmcydmJUbVhqdzZ3MlBDNHYv
            VU9zWHplaTBCSXJYZ05nZmVjQnFLbncKewIL1PkQ3w4IpiF82gJUqlvecTxXDwOc
            c7+wt2ODanoMFg2ygi5grKkTk57TGggHQ3U4pyBXjdChwVq6Nq4ZoQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d2hgv8jl3kn3t26f68cpqxy26cd2qpk5af77x832ephn8qhszgssthjfjq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T09:31:17Z"
    mac: ENC[AES256_GCM,data:lLLiPZEyaoRpHRcLY4jfKCgyjRm1cwT+syvMeULRurdrmLSzA18SxjL5/55kxp6iZrfgKwI/yjedP2gaphCC4eOd/6ePJ6eox+PFuvt21ekeJwozttkVTH/1N1CIbWPPjMHofyrJ8whdOSTLQ5wsPDUvrJE5XRsMJdG1J/pNf0s=,iv:vzKbdJYMhLyqBROhA92akp3LapTikoVJBQJrCNfiWT0=,tag:n/NrYGpZffFeZrYqSojdDA==,type:str]
    version: 3.13.3
